"""init

Revision ID: 50b5064101c2
Revises: 123456789abc
Create Date: 2026-06-26 15:55:50.112017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b5064101c2'
down_revision: Union[str, None] = '123456789abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_messages_conversation'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('idx_conversations_member'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('family_id', sa.NUMERIC(), nullable=False),
    sa.Column('member_id', sa.NUMERIC(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_conversations_member'), 'conversations', ['member_id', 'updated_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('conversation_id', sa.NUMERIC(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_messages_conversation'), 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
