"""init_all

Revision ID: 8b181bae74a5
Revises: 50b5064101c2
Create Date: 2026-06-26 15:56:04.966412

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8b181bae74a5"
down_revision: Union[str, None] = "50b5064101c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=True),
        sa.Column("member_id", sa.UUID(), nullable=True),
        sa.Column("actor_firebase_uid", sa.String(length=255), nullable=False),
        sa.Column("actor_role", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=200), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("endpoint", sa.String(length=500), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("result", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audit_actor", "audit_logs", ["actor_firebase_uid", "created_at"], unique=False)
    op.create_index("idx_audit_family", "audit_logs", ["family_id", "created_at"], unique=False)
    op.create_table(
        "families",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("primary_user_id", sa.String(length=255), nullable=False),
        sa.Column("subscription_tier", sa.String(length=50), nullable=False),
        sa.Column("subscription_valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("health_baseline_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_families_primary_user", "families", ["primary_user_id"], unique=False)
    op.create_table(
        "family_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("firebase_uid", sa.String(length=255), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("date_of_birth", sa.Text(), nullable=True),
        sa.Column("gender", sa.String(length=50), nullable=True),
        sa.Column("relationship", sa.String(length=100), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("preferred_language", sa.String(length=10), nullable=False),
        sa.Column("health_profile_complete", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_members_family", "family_members", ["family_id"], unique=False)
    op.create_index("idx_members_firebase_uid", "family_members", ["firebase_uid"], unique=False)
    op.create_table(
        "memory_operations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=True),
        sa.Column("operation_type", sa.String(length=50), nullable=False),
        sa.Column("source_entity_type", sa.String(length=100), nullable=True),
        sa.Column("source_entity_id", sa.UUID(), nullable=True),
        sa.Column("cognee_memory_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_memory_ops_entity", "memory_operations", ["source_entity_type", "source_entity_id"], unique=False
    )
    op.create_index("idx_memory_ops_family", "memory_operations", ["family_id", "created_at"], unique=False)
    op.create_table(
        "consultations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("escalation_id", sa.UUID(), nullable=True),
        sa.Column("consultation_type", sa.String(length=100), nullable=False),
        sa.Column("specialty", sa.String(length=200), nullable=True),
        sa.Column("doctor_name", sa.Text(), nullable=True),
        sa.Column("doctor_id", sa.UUID(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("ai_brief", sa.Text(), nullable=True),
        sa.Column("ai_brief_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consultation_notes", sa.Text(), nullable=True),
        sa.Column("follow_up_required", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_consultations_member", "consultations", ["member_id", "scheduled_at"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_conversations_member", "conversations", ["member_id", "updated_at"], unique=False)
    op.create_table(
        "daily_checkins",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("checkin_date", sa.Date(), nullable=False),
        sa.Column(
            "checkin_time", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("domain", sa.String(length=100), nullable=False),
        sa.Column("raw_response", sa.Text(), nullable=True),
        sa.Column("structured_data", sa.Text(), nullable=True),
        sa.Column("ai_initiated", sa.Boolean(), nullable=False),
        sa.Column("coordinator_decision_id", sa.UUID(), nullable=True),
        sa.Column("memory_ingested", sa.Boolean(), nullable=False),
        sa.Column("memory_ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id", "checkin_date", "domain", name="uq_checkin_member_date_domain"),
    )
    op.create_index("idx_checkins_family_date", "daily_checkins", ["family_id", "checkin_date"], unique=False)
    op.create_index("idx_checkins_member_date", "daily_checkins", ["member_id", "checkin_date"], unique=False)
    op.create_table(
        "diagnoses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("condition_name", sa.Text(), nullable=False),
        sa.Column("icd_code", sa.String(length=20), nullable=True),
        sa.Column("diagnosis_type", sa.String(length=100), nullable=False),
        sa.Column("diagnosed_date", sa.Date(), nullable=True),
        sa.Column("diagnosed_by", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("source_consultation_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_diagnoses_member", "diagnoses", ["member_id", "status"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("document_type", sa.String(length=100), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=True),
        sa.Column("gcs_path", sa.Text(), nullable=False),
        sa.Column("gcs_bucket", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("processing_status", sa.String(length=50), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("structured_data", sa.Text(), nullable=True),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column("issued_by", sa.Text(), nullable=True),
        sa.Column("memory_ingested", sa.Boolean(), nullable=False),
        sa.Column("memory_ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_documents_member_type", "documents", ["member_id", "document_type", "created_at"], unique=False
    )
    op.create_index("idx_documents_processing", "documents", ["processing_status", "created_at"], unique=False)
    op.create_table(
        "escalation_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column(
            "triggered_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("triggering_signals", sa.JSON(), nullable=False),
        sa.Column("convergence_score", sa.Float(), nullable=False),
        sa.Column("recommended_specialty", sa.String(length=200), nullable=False),
        sa.Column("escalation_reason", sa.Text(), nullable=False),
        sa.Column("urgency_level", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("consultation_id", sa.UUID(), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_escalations_member", "escalation_events", ["member_id", "triggered_at"], unique=False)
    op.create_index("idx_escalations_pending", "escalation_events", ["family_id", "status"], unique=False)
    op.create_table(
        "health_baselines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("domain", sa.String(length=100), nullable=False),
        sa.Column("baseline_data", sa.Text(), nullable=True),
        sa.Column(
            "calculated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("data_points_count", sa.Integer(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id", "domain", name="uq_baseline_member_domain"),
    )
    op.create_index("idx_baselines_member_domain", "health_baselines", ["member_id", "domain"], unique=False)
    op.create_table(
        "health_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("metric_type", sa.String(length=100), nullable=False),
        sa.Column("value_numeric", sa.Float(), nullable=True),
        sa.Column("value_systolic", sa.Float(), nullable=True),
        sa.Column("value_diastolic", sa.Float(), nullable=True),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("wearable_device_id", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_metrics_member_type", "health_metrics", ["member_id", "metric_type", "recorded_at"], unique=False
    )
    op.create_table(
        "medications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("generic_name", sa.Text(), nullable=True),
        sa.Column("dosage", sa.Text(), nullable=True),
        sa.Column("frequency", sa.Text(), nullable=True),
        sa.Column("prescribed_by", sa.Text(), nullable=True),
        sa.Column("prescribed_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("indication", sa.Text(), nullable=True),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_medications_member_active", "medications", ["member_id", "is_active"], unique=False)
    op.create_table(
        "watcher_signals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("watcher_domain", sa.String(length=100), nullable=False),
        sa.Column("signal_date", sa.Date(), server_default=sa.text("(CURRENT_DATE)"), nullable=False),
        sa.Column("signal_type", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("signal_payload", sa.JSON(), nullable=False),
        sa.Column("deviation_from_baseline", sa.Float(), nullable=True),
        sa.Column("trend_direction", sa.String(length=20), nullable=True),
        sa.Column("supporting_data", sa.JSON(), nullable=True),
        sa.Column("surfaced", sa.Boolean(), nullable=False),
        sa.Column("surfaced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_signals_member_domain", "watcher_signals", ["member_id", "watcher_domain", "signal_date"], unique=False
    )
    op.create_index(
        "idx_signals_unsurfaced", "watcher_signals", ["family_id", "surfaced", "severity", "created_at"], unique=False
    )
    op.create_table(
        "coordinator_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("decision_date", sa.Date(), server_default=sa.text("(CURRENT_DATE)"), nullable=False),
        sa.Column("selected_domain", sa.String(length=100), nullable=False),
        sa.Column("selection_reason", sa.String(length=100), nullable=False),
        sa.Column("selected_signal_ids", sa.JSON(), nullable=False),
        sa.Column("suppressed_domains", sa.JSON(), nullable=True),
        sa.Column("checkin_count_today", sa.Integer(), nullable=False),
        sa.Column("user_busy_signal", sa.Boolean(), nullable=False),
        sa.Column("checkin_generated", sa.Text(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["daily_checkins.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id", "decision_date", "selected_domain", name="uq_coordinator_member_date_domain"),
    )
    op.create_index(
        "idx_coordinator_member_date", "coordinator_decisions", ["member_id", "decision_date"], unique=False
    )
    op.create_table(
        "medication_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("medication_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["medications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["family_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_med_logs_member_date", "medication_logs", ["member_id", "scheduled_time"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_messages_conversation", "messages", ["conversation_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_messages_conversation", table_name="messages")
    op.drop_table("messages")
    op.drop_index("idx_med_logs_member_date", table_name="medication_logs")
    op.drop_table("medication_logs")
    op.drop_index("idx_coordinator_member_date", table_name="coordinator_decisions")
    op.drop_table("coordinator_decisions")
    op.drop_index("idx_signals_unsurfaced", table_name="watcher_signals")
    op.drop_index("idx_signals_member_domain", table_name="watcher_signals")
    op.drop_table("watcher_signals")
    op.drop_index("idx_medications_member_active", table_name="medications")
    op.drop_table("medications")
    op.drop_index("idx_metrics_member_type", table_name="health_metrics")
    op.drop_table("health_metrics")
    op.drop_index("idx_baselines_member_domain", table_name="health_baselines")
    op.drop_table("health_baselines")
    op.drop_index("idx_escalations_pending", table_name="escalation_events")
    op.drop_index("idx_escalations_member", table_name="escalation_events")
    op.drop_table("escalation_events")
    op.drop_index("idx_documents_processing", table_name="documents")
    op.drop_index("idx_documents_member_type", table_name="documents")
    op.drop_table("documents")
    op.drop_index("idx_diagnoses_member", table_name="diagnoses")
    op.drop_table("diagnoses")
    op.drop_index("idx_checkins_member_date", table_name="daily_checkins")
    op.drop_index("idx_checkins_family_date", table_name="daily_checkins")
    op.drop_table("daily_checkins")
    op.drop_index("idx_conversations_member", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("idx_consultations_member", table_name="consultations")
    op.drop_table("consultations")
    op.drop_index("idx_memory_ops_family", table_name="memory_operations")
    op.drop_index("idx_memory_ops_entity", table_name="memory_operations")
    op.drop_table("memory_operations")
    op.drop_index("idx_members_firebase_uid", table_name="family_members")
    op.drop_index("idx_members_family", table_name="family_members")
    op.drop_table("family_members")
    op.drop_index("idx_families_primary_user", table_name="families")
    op.drop_table("families")
    op.drop_index("idx_audit_family", table_name="audit_logs")
    op.drop_index("idx_audit_actor", table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
